### ISSUE TITLE
Create a "More Information" page with useful resources

### ISSUE THREAD

**Issue by arbolitoloco** [arbolitoloco/color-blind-simulator#2]
A new HTML file would have to be created to add information on different kinds of color vision defficiency and useful links.

Ideally, this new file would be linked to somewhere in the `index.html`.

**Comment by muhdarifrawi** [comment]
Hey there! Is it okay if I worked on this?

**Comment by arbolitoloco** [comment]
@muhdarifrawi Feel free to get it started! Thank you so much!

**Comment by muhdarifrawi** [comment]
@arbolitoloco Thank you so much! It's my first time doing this. So nervous and excited 😆

**Comment by arbolitoloco** [comment]
@muhdarifrawi No need to be nervous, it looks daunting at first, but I promise it is smoother than it looks. If you need help, don't hesitate to ask.

**Comment by muhdarifrawi** [comment]
@arbolitoloco Thanks again. Will let you know if I get into any issues. 😊

**Comment by arbolitoloco** [comment]
Closed by PR #17, thank you @muhdarifrawi!
