### ISSUE TITLE
Restyle "download button" to make it more user-friendly

### ISSUE THREAD

**Issue by arbolitoloco** [arbolitoloco/color-blind-simulator#4]
Currently, the button is flat and awkward. Ideally should be restyled to make it easier for users to understand that it is a button.

**Comment by darkshredder** [comment]
I would like to take up this issue

**Comment by arbolitoloco** [comment]
@darkshredder Thank you for your help! Feel free to tackle this, please.

**Comment by arbolitoloco** [comment]
@MrValraven If you'd like, feel free to add a 'download' icon to the button to improve it further. Thank you!

**Comment by codewithvk** [comment]
Can you more describe now what you should need?
I am happy to work with it.

**Comment by arbolitoloco** [comment]
> Can you more describe now what you should need?
> I am happy to work with it.

Hi @codewithvk I'm so sorry I didn't reply in time, I had a hectic month. There have been some changes applied to the button thanks to @MrValraven and @darkshredder. If you're still up to do it, I could use some restyling to the "file upload" button and input field. Thanks!
