### ISSUE TITLE
Create dynamic contributors section

### ISSUE THREAD

**Issue by arbolitoloco** [arbolitoloco/color-blind-simulator#7]
Dynamically pull list of this repo's contributors through [Github's API](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#list-repository-contributors) and display their information (avatar, profile url, username) in a gallery to be included in the `index.html` and in the `README.md`.

**Comment by RCarvalhoDan** [comment]
I would like to take up this issue.

**Comment by RCarvalhoDan** [comment]
WIP

**Comment by arbolitoloco** [comment]
This was closed by PR #14, thank you @RCarvalhoDan!
